version: '3.7'

services:
  web:
    build: 
      context: ./granja
      dockerfile: Dockerfile.prod
    command: gunicorn granja.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./granja/static:/usr/src/app/web/static
      - ./granja/media:/usr/src/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
  db_prod:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 12345

  pgadmin:
    container_name: pgadminps_prod
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: daferarte@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8082:80"
  nginx:
    build: ./nginx
    volumes:
      - ./granja/static:/usr/src/app/web/static
      - ./granja/media:/usr/src/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data: