version: '3.7'

services:
  granja:
    container_name: granja
    build: ./granja
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./granja/:/usr/src/granja/
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev
  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 12345

  pgadmin:
    container_name: pgadminps
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: daferarte@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8081:80"
volumes:
  postgres_data: