# Generated by Django 5.0.6 on 2024-06-29 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cost', models.FloatField(verbose_name='Precio producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de producto')),
                ('image', models.ImageField(blank=True, default='null', null=True, upload_to='categories', verbose_name='Foto')),
                ('datePacked', models.DateField(verbose_name='Fecha de empaquetado')),
                ('expiryDate', models.DateField(verbose_name='Fecha de vencimiento')),
                ('expiryTime', models.TimeField(verbose_name='Hora de expiración')),
                ('public', models.BooleanField(default=False, verbose_name='¿Publicado?')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('categorie', models.ManyToManyField(blank=True, to='products.categories', verbose_name='Categorías')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-create_at'],
            },
        ),
    ]
